message=input("Entrez le message de l'Empire :")
messageofempire=message.lower()
A=messageofempire.count("a")
E=messageofempire.count("e")
I=messageofempire.count("i")
O=messageofempire.count("o")
U=messageofempire.count("u")
Y=messageofempire.count("y")
print(f" Les coordonnees galactiques sont {A}.{E}.{I}.{O}.{U}.{Y}.")
